---
name: package-updater
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
  pull_request:

jobs:
  package-updater:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Nim environment
        uses: jiro4989/setup-nim-action@v1.1.4

      - name: Update packages
        run: "nimble refresh && nix run .#package-updater"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.13.1
        with:
          commit_message: Update packages
          commit_options: "--no-verify"
